user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 768;  # Máximo de conexões simultâneas por worker
}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;  # Definição de tipos MIME
    default_type application/octet-stream;

    # Logs globais de acesso e erro
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Configuração de compactação
    gzip on;

    # Incluir os arquivos de configuração do virtual host (como "default")
    include /etc/nginx/sites-enabled/*;
}