display_errors = On
log_errors = On
error_log = /var/log/php/error.log
max_execution_time = 300
memory_limit = 256M
post_max_size = 100M
upload_max_filesize = 100M
date.timezone = UTC
variables_order = "EGPCS"
