apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-configs
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    {{ .Files.Get "backend/confs/nginx.conf" | nindent 4 }}
  default: |
    {{ .Files.Get "backend/confs/default" | nindent 4 }}
  php.ini: |
    {{ .Files.Get "backend/confs/php.ini" | nindent 4 }}
  custom.conf: |
    {{ .Files.Get "backend/confs/custom.conf" | nindent 4 }}
  supervisor.conf: |
    {{ .Files.Get "backend/confs/supervisord.conf" | nindent 4 }}
  entrypoint.sh: |
    {{ .Files.Get "backend/confs/entrypoint.sh" | nindent 4 }}
  my.conf: |
    {{ .Files.Get "backend/confs/my.conf" | nindent 4 }}
  php-fpm.conf: |
    {{ .Files.Get "backend/confs/php-fpm.conf" | nindent 4 }}
  phpfpm.ini: |
    {{ .Files.Get "backend/confs/phpfpm.ini" | nindent 4 }}