apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
    tier: backend
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.backend.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.backend.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        environment: {{ .Values.environment }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: backend
              topologyKey: "kubernetes.io/hostname"
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - database
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy | default "IfNotPresent" }}"
          resources:
            requests:
              memory: "{{ .Values.backend.resources.requests.memory }}"
              cpu: "{{ .Values.backend.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.backend.resources.limits.memory }}"
              cpu: "{{ .Values.backend.resources.limits.cpu }}"
          ports:
            - name: http
              containerPort: {{ .Values.backend.containerPort }}
              protocol: TCP

          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config-env  # ConfigMap de ambiente

          volumeMounts:
            - name: config-app-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: config-app-volume
              mountPath: /etc/php/7.4/fpm/php.ini
              subPath: php.ini
            - name: config-app-volume
              mountPath: /etc/supervisor/conf.d/supervisord.conf
              subPath: supervisord.conf
            - name: config-app-volume
              mountPath: /etc/confs/entrypoint.sh
              subPath: entrypoint.sh
              mode: 0755

      volumes:
        - name: config-app-volume
          configMap:
            name: {{ .Release.Name }}-config-app  # ConfigMap de configuração da aplicação

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
spec:
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mysql.containerPort }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.secretName }}
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.secretName }}
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.secretName }}
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/
              readOnly: true
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ .Values.mysql.persistence.existingClaim }}
        - name: init-sql
          configMap:
            name: {{ .Values.mysql.initConfigMap }}