apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.secrets.rootPassword | b64enc }}
  MYSQL_HOST: {{ .Values.mysql.secrets.host | b64enc }}
  MYSQL_DATABASE: {{ .Values.mysql.secrets.database | b64enc }}
  MYSQL_USER: {{ .Values.mysql.secrets.user | b64enc }}
  MYSQL_PASSWORD: {{ .Values.mysql.secrets.password | b64enc }}