apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend
  type: {{ .Values.service.backend.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.backend.containerPort }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: {{ .Values.service.mysql.port | default 3306 }} 
      targetPort: {{ .Values.service.mysql.targetPort | default 3306 }} 
  type: {{ .Values.service.mysql.type | default "ClusterIP" }} 